### PR TITLE
Append http prefix to the gateway URL

### LINKED ISSUE #279: Check for invalid URL in faas-cli login
When using `faas-cli login` without the `http(s)://` portion of the URL, an unhandled exception occurs:

```
$ faas-cli login -u admin -p <pw> -g <endpoint-ip>:31112

WARNING! Using --password is insecure, consider using: cat ~/faas_pass.txt | faas-cli login -u user --password-stdin

Calling the OpenFaaS server to validate the credentials...

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6d0cb2]
```

## Expected Behaviour

The error needs to be handled, in the same way that it is in the fix for the `deploy` and `delete` commands: 

https://github.com/openfaas/faas-cli/commit/fa9e08d4c545399c6d81f3827682f34c116d7af1#diff-32a00314934dd566c4dbf7a14c10ce85R77

## Current Behaviour

Segmentation fault occurs if invalid URL is supplied

## Possible Solution

Check the `err` variable that is returned by `NewRequest()`, currently `_` is used instead of `err`:

https://github.com/openfaas/faas-cli/blob/cadf7dea543d149b1932f9636dc24805de8643a9/commands/login.go#L110

## Steps to Reproduce (for bugs)

1. Run `faas-cli login -u <user> -p <pw> -g <ip>:<port>` without `http(s)://` in front of `<ip>
2.
3.
4.

## Context

Ran into this while trying to log in to GKE cluster

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
GKE (Kubernetes 1.7.11-gke.1)

* Operating System and version (e.g. Linux, Windows, MacOS):
coreos

* Link to your project or a code example to reproduce issue:

### PR DESCRIPTION
**Pull request by stefanprodan**
fix #279

## Description
This PR allows the gateway URL to be specified in the `IP:PORT` format without HTTP/S.
If a protocol is not specified then HTTP will be used.

## Motivation and Context
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Tested on GKE with HTTP, HTTPS and IP:PORT

Before the fix:

```
./faas-cli login -u test -p test --gateway=163.172.143.209:31112
Calling the OpenFaaS server to validate the credentials...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x12de642]
```

After the fix:

```
./faas-cli login -u test -p test --gateway=163.172.143.209:31112
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: http://163.172.143.209:31112
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: commands/deploy.go [hunk 1]
```diff
@@ -299,6 +299,11 @@ func getGatewayURL(argumentURL string, defaultURL string, yamlURL string) string
 		gatewayURL = defaultURL
 	}
 
+	gatewayURL = strings.ToLower(strings.TrimRight(gatewayURL, "/"))
```
Comment (ericstoekl) [inline commands/deploy.go]: What about `https://`?

Comment (alexellis) [reply commands/deploy.go]: I don't think it will pick up https.. https will always need to be typed in separately but this should make testing quicker for us when we are on localhost etc and forget to add `http://` before `localhost:8080`
