### PR TITLE
Read gateway environment in logout command

### LINKED ISSUE #762: Logout command does not read `OPENFAAS_URL` env variable
Logout command does not check for `OPENFAAS_URL` environment variable and command need to pass it using `-g` or `--gateway` flag.

Screen Shot 2020-02-06 at 12 45 07 AM

## Expected Behaviour

It should use the `OPENFAAS_URL` value if `--gateway` flag is not passed. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

### PR DESCRIPTION
**Pull request by viveksyngh**
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Fixes #762 

## How Has This Been Tested?

I have tested on my local system.
```
./faas-cli logout
Gateway http://127.0.0.1:8080 not found in config
➜  faas-cli git:(master) ✗ export OPENFAAS_URL=http://127.0.0.1:31112
➜  faas-cli git:(master) ✗ ./faas-cli logout
credentials removed for http://127.0.0.1:31112
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: commands/logout.go [hunk 1]
```diff
@@ -29,8 +30,9 @@ func runLogout(cmd *cobra.Command, args []string) error {
 	if len(gateway) == 0 {
 		return fmt.Errorf("gateway cannot be an empty string")
 	}
+	gateway = strings.TrimSpace(gateway)
```
Comment (rgee0) [inline commands/logout.go]: Would it make sense for the trim come before the length check, or am I thinking too defensively?

If it does, then this may make sense in other commands.

Comment (alexellis) [reply commands/logout.go]: I like the suggestion, could it be worth raising separately from this PR as an issue?

Comment (viveksyngh) [reply commands/logout.go]: Yes we should trim spaces before the length check. I will create an issue to track this.
