### PR TITLE
Describe function command should include namespace in urls

### LINKED ISSUE #739: describe function command does not produce the correct url for the supplied namespace
The `faas-cli describe` command is namespace aware, but does not print the correct urls that include the `.<namespace>`

## Expected Behaviour

The output should include the url with the namespace

```sh
$ faas-cli describe --namespace beta travel-predictions
Name:                travel-predictions
Status:              Ready
...
Function process:
URL:                 https://example.com/function/travel-predictions.beta
```

## Current Behaviour

```sh
$ faas-cli describe --namespace beta travel-predictions
Name:                travel-predictions
Status:              Ready
...
Function process:
URL:                 https://example.com/function/travel-predictions
```

## Possible Solution

Update the `getFunctionURLs` method

## Steps to Reproduce (for bugs)

1. Deploy to kuberenets with namespace support, as done in these docs https://docs.openfaas.com/reference/namespaces/
2. Add a namespace `beta` 
```sh
kubectl create ns beta
kubectl annotate ns beta openfaas="true"
```
3. Deploy a function to beta `faas-cli store deploy NodeInfo -n beta`
4. Describe that function `faas-cli describe -n beta nodeinfo`

## Context

Relates to openfaas/faas-netes#511

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
`0.11.2`

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
faas-netes in GKE

### PR DESCRIPTION
**Pull request by codegold79**
## Description

Name spaces have been appended to both the url and async url in the command package function getFunctionURLs.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes #739 

## How Has This Been Tested?

I have created a table test that ensures the expected URLs are generated for DNSs with and without ports, as well as for functions with and without namespaces.

I also built the faas-cli app on my MacOS using MiniKube and OpenFaaS installed with k3sup. I then enabled namespaces, a new feature as of this comment. I followed the instructions in the following pages to set up my system:
* https://docs.openfaas.com/deployment/kubernetes
* https://docs.openfaas.com/reference/namespaces/

I ran the describe command with `./faas-client describe <function> -n <namespace>` and `./faas-client describe <function>` and saw the expected URLs. See screenshot:
Screen Shot 2019-12-19 at 5 02 25 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by codegold79** [comment]
Build failed. I'll look at the logs and see what failed tomorrow.

**Comment by LucasRoesler** [comment]
@codegold79 The CI error is 

```
Run "gofmt -s -w" on your Golang code
The command '/bin/sh -c test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }' returned a non-zero code: 1
Makefile:13: recipe for target 'build' failed
```

Run `make local-fmt` and address whatever it says and the PR should be good

**Comment by codegold79** [comment]
VS Code automatically runs `go fmt` when I save the file, but since all the formatting errors were invisible white spaces, I forgot to save. :doh: And then, I forgot to sign off. Had to force push. Bah. I blame morning brain fog.

Thanks @LucasRoesler for your help in this first PR for this repo. While waiting for code review, I'll go and see if I can wrap my head around what's happening with faas-containerd or openfaas/certifier.

File: commands/describe_test.go [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+	}
+
+	for _, tc := range cases {
+		t.Run(tc.name, func(t *testing.T) {
+			url, asyncURL := getFunctionURLs(tc.gateway, tc.functionName, tc.functionNamespace)
+
+			if url != tc.expectedURL || asyncURL != tc.expectedAsyncURL {
+				t.Fatalf("incorrect URL(s):\n got %s and %s\n expected %s and %s\n", url, asyncURL, tc.expectedURL, tc.expectedAsyncURL)
+			}
+			t.Log("Expected URLs were generated: " + url + " and " + asyncURL + ".")
```
Comment (alexellis) [inline commands/describe_test.go]: What is the purpose of this log statement?

File: commands/describe_test.go [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+		{"secure site", "https://example.com", "nodeinfo", "beta", "https://example.com/function/nodeinfo.beta", "https://example.com/async-function/nodeinfo.beta"},
+		{"no namespace", "https://example.com:31112", "nodeinfo", "", "https://example.com:31112/function/nodeinfo", "https://example.com:31112/async-function/nodeinfo"},
+	}
+
+	for _, tc := range cases {
+		t.Run(tc.name, func(t *testing.T) {
+			url, asyncURL := getFunctionURLs(tc.gateway, tc.functionName, tc.functionNamespace)
+
+			if url != tc.expectedURL || asyncURL != tc.expectedAsyncURL {
+				t.Fatalf("incorrect URL(s):\n got %s and %s\n expected %s and %s\n", url, asyncURL, tc.expectedURL, tc.expectedAsyncURL)
```
Comment (alexellis) [inline commands/describe_test.go]: Please use verbiage of want/got instead

I think we can do without the newlines too, perhaps use `%q` if you need to see the exact quoted values.

File: commands/describe_test.go (hunk 1 above)
Comment (codegold79) [reply commands/describe_test.go]: I was thinking having a log of what went well would distinguish it from a test that didn't have tests and passed. I encountered PASS when I mistakenly had no tests, ran the test, and the result was PASS, because nothing failed.

There's a difference between PASS because there was no failure, and actually PASS because the tests were successful.

However, if it's not useful, not idiomatic, nor per the style of this repository, I'll remove the `t.Log`.

File: commands/describe_test.go (hunk 2 above)
Comment (codegold79) [reply commands/describe_test.go]: Cool, thanks for the tip, I'll fix this Monday.

File: commands/describe_test.go (hunk 1 above)
Comment (codegold79) [reply commands/describe_test.go]: I looked at several other tests in faas-cli/commands, and I didn't see any that logged the details of what resulted in a test PASS. So, for consistency, I'll remove the line beginning with `t.Log`.

File: commands/describe_test.go (hunk 2 above)
Comment (codegold79) [reply commands/describe_test.go]: Done.

File: commands/describe_test.go (hunk 1 above)
Comment (alexellis) [reply commands/describe_test.go]: Thanks

File: commands/describe.go [hunk 3]
```diff
@@ -109,9 +109,16 @@ func runDescribe(cmd *cobra.Command, args []string) error {
 	return nil
 }
 
-func getFunctionURLs(gateway string, functionName string) (string, string) {
+func getFunctionURLs(gateway string, functionName string, functionNamespace string) (string, string) {
 	gateway = strings.TrimRight(gateway, "/")
-	return gateway + "/function/" + functionName, gateway + "/async-function/" + functionName
+	url := gateway + "/function/" + functionName + "." + functionNamespace
```
Comment (alexellis) [inline commands/describe.go]: What happens here when the namespace is `""`?

File: commands/describe.go [hunk 4]
```diff
@@ -109,9 +109,16 @@ func runDescribe(cmd *cobra.Command, args []string) error {
...
+	asyncURL := gateway + "/async-function/" + functionName + "." + functionNamespace
+
+	// Remove dot for functions without namespaces.
+	url = strings.TrimRight(url, ".")
```
Comment (alexellis) [inline commands/describe.go]: Might be better to add conditionally, rather than mutating the string and then trimming, this seems like a bit of a hack.

Would something like this work? The existing tests should continue to work. 

```
if len(functionNamespace) > 0 {

}
```

File: commands/describe.go (hunk 3 above)
Comment (codegold79) [reply commands/describe.go]: The URLs end up having a dot at the end if namespace has nil value.

File: commands/describe.go (hunk 4 above)
Comment (codegold79) [reply commands/describe.go]: Yes, I think it would work. Having an if statement also makes the comment "// Remove dot..." unnecessary. I'll remove that comment.

Comment (codegold79) [reply commands/describe.go]: I ended up writing a simpler `if functionNamespace == "" {...}`, which doesn't have a `len()` function call.

File: commands/describe.go [hunk 5]
```diff
@@ -109,9 +109,20 @@ func runDescribe(cmd *cobra.Command, args []string) error {
...
 }
 
-func getFunctionURLs(gateway string, functionName string) (string, string) {
+func getFunctionURLs(gateway string, functionName string, functionNamespace string) (string, string) {
+	var url, asyncURL string
+
 	gateway = strings.TrimRight(gateway, "/")
-	return gateway + "/function/" + functionName, gateway + "/async-function/" + functionName
+
+	if functionNamespace == "" {
```
Comment (alexellis) [inline commands/describe.go]: I think you could do away with this repetition in each block. What if you just decide the suffix here and have it as an empty string when there is no namespace? That also means you can do away with the else

Comment (codegold79) [reply commands/describe.go]: I like your suggestion--I think the code looks much cleaner now.
