### PR TITLE
Fix generate command for read-only root filesystem setting

### LINKED ISSUE #928: Read-only root filesystem settings is lost when using `faas-cli generate`
The read-only root filesystem configuration from the stack.yml is not included in CRDs generated with `faas-cli generate`

## Expected Behaviour

When `readonly_root_filesystem` is set in the stack.yml configuration of a function it should also be included in the spec of the CRD generated with `faas-cli generate`

stack.yml:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```

CRD:
```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: python3-http-fn
  namespace: openfaas-fn
spec:
  name: python3-http-fn
  image: welteki2/python3-http-fn:latest
  readOnlyRootFilesystem: true
```

## Current Behaviour

The `readonly_root_filesystem` setting in a stack.yml configuration is not included in the CRD after running `faas-cli generate`.

stack.yml:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```

CRD:
```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: python3-http-fn
  namespace: openfaas-fn
spec:
  name: python3-http-fn
  image: welteki2/python3-http-fn:latest
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1. Create a stack.yml file
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```
3. Run `faas-cli generate -f stack.yml`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  fcf50cef7b3510d93dd109606fb300705bb509f2
 version: 0.14.6

Gateway
 uri:     http://gateway.cromulon.local:8000
 version: 0.2.0
 sha:     1676b1135f10e1487d037ef7b0c7a2783fdace8e


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.1.6 
 sha:           532dc025e52444f625e32b38ac49578cf305cbeb
```
* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

### PR DESCRIPTION
**Pull request by welteki**
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>

## Description

Make sure the readonly_root_filesystem setting is included in the resulting CRD when running `faas-cli generate`.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Closes #928 

## How Has This Been Tested?

1. Verified output of generate command

Stack.yml:

```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```

Generated CRD:

```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: python3-http-fn
  namespace: openfaas-fn
spec:
  name: python3-http-fn
  image: welteki2/python3-http-fn:latest
  readOnlyRootFilesystem: true

```
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: commands/generate_test.go [hunk 1]
```diff
@@ -202,6 +202,35 @@ spec:
 		Branch:     "",
 		Version:    "",
 	},
+	{
+		Name: "Read-only root filesystem",
```
Comment (alexellis) [inline commands/generate_test.go:206]: Is there an equivalent test that shows it's not outputted? We may already have that.

Comment (alexellis) [reply commands/generate_test.go:206]: If you're OK that it's covered then we can leave it as it is.
