### PR TITLE
Enable keep alive on login - fix for TLS Ingress (L7 LB)

### LINKED ISSUE #245: Login is failing with TLS Ingress
Login is failing with TLS Ingress on GCP L7 LB

## Expected Behaviour
Do login

## Current Behaviour
Timeout due to Keep Alive being disabled 

## Possible Solution
Enable Keep Alive

## Steps to Reproduce (for bugs)
1. Deploy OpenFaaS on GKE 
2. Setup Gateway TLS via Ingress 
3. Try to login using the HTTPS endpoint

### PR DESCRIPTION
**Pull request by stefanprodan**
Fix #245

## How Has This Been Tested?
Tested on GKE with TLS Ingress and L7 load balancer 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Change sounds ok to me.. why didn't we see this before?

**Comment by stefanprodan** [comment]
We didn't see it because some LBs like Caddy will accept Keep Alive off some not

File: commands/login.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func runLogin(cmd *cobra.Command, args []string) error {
 func validateLogin(url string, user string, pass string) error {
 	// TODO: provide --insecure flag for this
```
Comment (alexellis) [inline commands/login.go]: What about the todo?
